import type { Metadata } from 'next';
import { Inter, Geist } from 'next/font/google';

import { TooltipProvider, DirectionProvider, Toaster } from '@/components/ui';
import './globals.css';
import { cn } from '@/lib';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-sans', geist.variable)} dir="ltr">
      <body className={inter.className}>
        <DirectionProvider direction="ltr">
          <TooltipProvider>{children}</TooltipProvider>
        </DirectionProvider>
        <Toaster />
      </body>
    </html>
  );
}
