import type { Metadata } from 'next';
import { Inter, Geist } from 'next/font/google';

import {
  MessageScrollerProvider,
  TooltipProvider,
  DirectionProvider,
  Toaster,
} from '@/components/ui';
import { cn } from '@/lib';
import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-sans', geist.variable)} dir="ltr">
      <body className={inter.className}>
        <DirectionProvider direction="ltr">
          <MessageScrollerProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </MessageScrollerProvider>
        </DirectionProvider>
        <Toaster />
      </body>
    </html>
  );
}
